sudo: true
dist: trusty
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer test

before_install:
  - sudo apt-get update
  - sudo apt-get -y --reinstall install libwebp-dev
  - sudo apt-get -y --reinstall install imagemagick
  - printf "\n" | pecl install imagick-beta
  - composer install
